INSERT INTO PRODUCTS
VALUES (1, 'product1', NOW(), 1, 1);
INSERT INTO PRODUCTS
VALUES (2, 'product2', NOW(), 2, 1);
INSERT INTO PRODUCTS
VALUES (3, 'product3', NOW(), 3, 2);
INSERT INTO CAMPAIGNS
VALUES (1, 'Levis', 1, 200.0, NOW());
INSERT INTO CAMPAIGNS
VALUES (2, 'Tnuva', 2, 500.0, NOW());
INSERT INTO CAMPAIGNS_PRODUCTS
VALUES (1, 1, 1);
INSERT INTO CAMPAIGNS_PRODUCTS
VALUES (2, 1, 2);
