DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS CARDS
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    name   VARCHAR(100),
    pan    VARCHAR(100),
    expiry VARCHAR(5),
    cvv    VARCHAR(3)
);



CREATE TABLE IF NOT EXISTS CARDHOLDERS
(
    id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(100),
    email VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS INVOICES
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS TRASACTIONS
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice      VARCHAR(100) NOT NULL,
    amount       DOUBLE       NOT NULL,
    currency     VARCHAR(3)   NOT NULL,
    cardholderid BIGINT,
    cardid       BIGINT
);
