DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS CARDS
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    pan        VARCHAR(100) NOT NULL,
    expirydate VARCHAR(5)   NOT NULL,
    cvv        VARCHAR(3)   NOT NULL
);



CREATE TABLE IF NOT EXISTS CARDHOLDERS
(
    id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS INVOICES
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS TRASACTIONS
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice      VARCHAR(100) NOT NULL,
    amount       DOUBLE       NOT NULL,
    currency     VARCHAR(3)   NOT NULL,
    cardholderid BIGINT       NOT NULL,
    cardid       BIGINT       NOT NULL
);
